# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/j-test" 
# the subpath of your site, e.g. /blog/
url: "http://angeliquejw.github.io/j-test"
# the base hostname & protocol for your site
encoding: utf-8
timezone: America/New_York
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
highlighter: rouge
markdown: kramdown
