# Site settings
title: Dev Journal
description: "Developer notes and ideas by Angelique Weger"
baseurl: "/j-test" 
# the subpath of your site, e.g. /blog/
url: "http://angeliquejw.github.io/j-test"
# the base hostname & protocol for your site
encoding: utf-8
timezone: America/New_York

# Conversion
highlighter: rouge
markdown: kramdown
excerpt_separator: <!--more-->
